### ISSUE TITLE
Typescript usage

### ISSUE THREAD

**Issue by osmestad** [enjikaka/webact#4]
For usage in Typescript I think some of the types are a bit wrong, I think:
`registerFunctionComponent(callback: Function, { metaUrl: ?string, observedAttributes: ?string[] })`
Should maybe be:
`registerFunctionComponent(callback: Function, { metaUrl?: string, observedAttributes?: string[], name?: string })`
to allow passing only some of the options?
(`name` is missing in the readme)

**Comment by enjikaka** [comment]
Should be fixed in 6ac1fa6 :) JSDoc doesn't support optional keys in the notation I used; but when using typedef it's possible. Changed to that.
